### ISSUE TITLE
Missing data in MIR-ST500

### ISSUE THREAD

**Issue by chenxinglili** [york135/singing_transcription_ICASSP2021#2]
I tried to download the MIR-ST500 dataset, but found that some of the data could not be downloaded from YouTube (deleted or without permission). 

For example, 38, 50, 55, 60, 71, 81, 93, 126, 127, 129, 141, 150, 172, 201, 205, 215, 216, 221, 232, 240, 255, 257, 261, 264, 278, 284, 285, 290, 291, 304, 307, 319, 321, 325, 332, 333, 337, 359, 375, 381 in the train set. 
411, 417, 434, 435, 436, 439, 443, 445, 449, 460, 486, 495 in the test set.

Due to the lack of data,  I found I can not obtain convincing results. How can I get the missing data?

Hope to get your help and reply.

**Comment by york135** [comment]
OK. I've sent the link of the dataset to you.

**Comment by LCF2764** [comment]
以下编号的youtube链接已经失效了，请问你还有其他链接吗？有的话发我一份，谢谢！
38, 50, 55, 60, 81, 126, 127, 129, 141, 150, 172, 201, 205, 215, 216, 221, 232, 240, 255, 257, 264, 278, 285, 291, 304, 319, 321, 325, 332, 333, 337, 350, 359, 375, 445

**Comment by york135** [comment]
> 以下编号的youtube链接已经失效了，请问你还有其他链接吗？有的话发我一份，谢谢！ 38, 50, 55, 60, 81, 126, 127, 129, 141, 150, 172, 201, 205, 215, 216, 221, 232, 240, 255, 257, 264, 278, 285, 291, 304, 319, 321, 325, 332, 333, 337, 350, 359, 375, 445

Please send an e-mail to me (junyou.wang@mirlab.org) and provide with your name and affiliation. Then, I will decide whether to give you the access or not. Thank you.
請寄信給我（junyou.wang@mirlab.org），告知你的名字與所屬單位，我會決定要不要發連結給你，謝謝。
